### PR TITLE
Fixed work paths, added blackPanther OS browser support

### PR DESCRIPTION
**Pull request by blackPantherOS**
Hi, I've made little modifications because the original script write to full the tmpfs

### CODE REVIEW

**Comment by paralib5** [comment]
Hi,
I took over your modifications after some adaptations:
$TMPDIR is now defined at the beginning of the script to allow easier modification in the future.
Use ~/.tmp instead to not clutter user's home directories.

I do not think that the log files cause problems on tmpfs, since they are very small. My assumption is that the following line to get HDD performance can cause overflows on some systems:
system("dd if=/dev/zero of=/tmp/dd_tempfile bs=1M count=1024 conv=fdatasync,notrunc >  $TMPDIR/dd.txt 2> $TMPDIR/dd.err.txt");

**Comment by blackPantherOS** [comment]
"My assumption is that the following line to get HDD performance can cause overflows on some systems:"
yes;-)
we are testing on many different hardware, and the original script full write the small tmpfs, new applications can't start

**Comment by paralib5** [comment]
There should be a test if the /tmp/ directory has enough space left before the 
`dd if=/dev/zero of=/tmp/dd_tempfile bs=1M count=1024` 
command is executed. If not, one could skip this command since it is not mandatorily needed for the test results.

**Comment by paralib5** [comment]
Corresponding check was added by
https://github.com/paralib5/lhg_scanner/commit/0686d9f449ef764aa531b99f0058b35dacf5bfba

**Pull request merged**
